networks: 
  postgresql:
    driver: bridge

services:
  db:
    image: "postgres:latest"
    container_name: "pgdb"
    restart: always
    environment:
      POSTGRES_USER: "usuario"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "aplicacao"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./App_Data/DB/:/var/lib/postgresql/data/
      - ./App_Data/:/tmp/
    networks:
      - postgresql

  runtime:
    image: mcr.microsoft.com/dotnet/runtime:7.0
    container_name: dotnet
    command: "dotnet /tmp/Program.dll"
    volumes:
      - ./bin/Release/net7.0/publish/:/tmp/
    depends_on:
      - db
    networks:
      - postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "mestre@ruan.com"
      PGADMIN_DEFAULT_PASSWORD: "123456789"
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
      PGADMIN_LISTEN_PORT: "8888"
    ports:
      - "8888:8888"
    expose:
      - "8888"
    depends_on:
      - db
    networks:
      - postgresql
