services:
  db:
    image: "postgres:latest"
    container_name: "pgdb"
    restart: always
    environment:
      POSTGRES_USER: "usuario"
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "aplicacao"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./App_Data/:/var/lib/postgresql/data/
  C#:
    image: mcr.microsoft.com/dotnet/runtime:7.0
    container_name: dotnet
    command: "dotnet /tmp/Program.dll"
    volumes:
        - ./bin/Release/net7.0/publish/:/tmp/